export const USERS_BASE_URL = "http://localhost:8080/api/v1/users"
export const PUBLIC_BASE_URL = "http://localhost:8080/api/v1/public"
export const BASE_URL = "http://localhost:8080/api/v1"
export const ROLE_ADMIN = "ROLE_ADMIN"
export const ROLE_USER = "ROLE_USER"